# Generated by Django 5.0.7 on 2024-10-28 00:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoblinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_name', models.CharField(default='base', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Goblin',
            fields=[
                ('goblinmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brain.goblinmodel')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            bases=('brain.goblinmodel',),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('goblinmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brain.goblinmodel')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            bases=('brain.goblinmodel',),
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.IntegerField()),
                ('audio_data', models.BinaryField()),
                ('transcription', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.transcriptionsession')),
            ],
        ),
    ]
