version: "3.8"

services:
  fastapi:
    build: ./goblin
    volumes:
      - ./goblin:/app  # Mount the application code to enable hot reload
    ports:
      - "8008:8008"  # Map the container port to the host port
    environment:
      - PORT=8008
