version: "3.8"

services:
  goblin:
    build: ./
    volumes:
      - ./:/app  # Mount the application code to enable hot reload
    ports:
      - "8008:8008"  # Map the container port to the host port
    environment:
      - PORT=8008
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6383:6379"
